### PR TITLE
Add support for onboard network devices

### PR DESCRIPTION
**Pull request by skovic**
This PR updates the refresh parser to support onboard network devices. In addition, guest_device related methods in the refresh parser were refactored, so future support for expansion cards will be easier to implement.

### CODE REVIEW

**Comment by skovic** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by skovic** [comment]
@miq-bot assign @rodneyhbrown7

**Comment by rodneyhbrown7** [comment]
LGTM.  Note that a PR is needed in the UI to change the "Network Adapters" table to "Network Devices"

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit c26fcbb20647948ee15c6f8a06213d270689d98c
Author: Rodney Brown <rodneyhbrown7@users.noreply.github.com>
Date:   Fri Nov 3 10:14:44 2017 -0400

    Merge pull request #105 from skovic/onboard-network-device-support
    
    Add support for onboard network devices
    (cherry picked from commit 6ce24afafe0df3c337bc9db56c6c84f71da84310)
```

**Pull request merged**
