### PR TITLE
Fetches nodes from cabinets instead of its own resource

### PR DESCRIPTION
**Pull request by terciodemelo**
Many of the current resource paths in LXCA API are being deprecated and will be discontinued soon. Thus, the way to fetch nodes through the REST API is using the `/cabinet` resource. This is how this the goal of this PR.

PS: We must wait the https://github.com/juliancheal/xclarity_client gem to support query strings through the merging of https://github.com/juliancheal/xclarity_client/pull/17, before merging this very PR.

### CODE REVIEW

**Comment by juliancheal** [comment]
I'll push a new ruby gem of the client now we have https://github.com/juliancheal/xclarity_client/pull/17

**Comment by terciodemelo** [comment]
Awesome, as soon as you do it I'll update the provider =]

**Comment by juliancheal** [comment]
Gem updated and pushed, this repo now using new gem version if you rebase :)

**Comment by terciodemelo** [comment]
Done =]

**Pull request merged**
