### PR TITLE
Adds LXCA event groups for event handling

### PR DESCRIPTION
**Pull request by lucashsilva**
This PR adds the custom LXCA event groups for filtering on physical server timelines. 
[Physical Server Events Filtering.pdf](https://github.com/ManageIQ/manageiq-providers-lenovo/files/1371973/Physical.Server.Events.Filtering.pdf)

### CODE REVIEW

**Comment by lucashsilva** [comment]
@juliancheal could you please take a look at this?

**Comment by agrare** [comment]
@lucashsilva this is failing CI, can you look into the failing test?

**Comment by lucashsilva** [comment]
@agrare I have just fixed the test

**Comment by walteraa** [comment]
Just a tip: @lucashsilva you shouldn't use Lenovo's  User Stories references("IDs") as branch name. Use a short User store description.

**Comment by lucashsilva** [comment]
Thanks a lot @walteraa

**Pull request merged**
