### PR TITLE
Adding and classifying error messages

### PR DESCRIPTION
**Pull request by matheuscmelo**
Adding error messages to settings.yml
This was possible by an automatic analysis of LXCA's documentation.

### CODE REVIEW

**Comment by matheuscmelo** [comment]
@miq-bot assign @CharlleDaniel

**Comment by agrare** [comment]
@matheuscmelo @CharlleDaniel if you add new sections to the event_groups you must update the specs on master otherwise it will cause test failures: https://travis-ci.org/ManageIQ/manageiq/jobs/413771753#L1010-L1019

**Comment by himdel** [comment]
This breaks a bunch of ui-classic specs on travis: https://gist.github.com/himdel/c7b682676542936c8e4533ee58da7ebb

(example https://travis-ci.org/ManageIQ/manageiq-ui-classic/jobs/413927437)

**Comment by himdel** [comment]
The error comes from not sticking to the schema, again... maybe we need a spec for that.

But, fix:

```diff
+diff --git a/config/settings.yml b/config/settings.yml
index 00d7d97..0897151 100644
--- a/config/settings.yml
+++ b/config/settings.yml
@@ -71,6 +71,7 @@
           - 'IMM0133'
           :detail:
           - 'PLAT0187'
+          :warning: []
           :name: Firmware
         :devices:
           :critical:
@@ -127,6 +128,7 @@
           - 'PLAT0520'
           :name: Devices
         :network:
+          :critical: []
           :detail:
           - 'IMM0056'
           - 'IMM0025'
@@ -143,6 +145,7 @@
           - 'IMM0013'
           - 'IMM0059'
         :login:
+          :critical: []
           :detail:
           - 'IMM0014'
           - 'IMM0154'
@@ -180,6 +183,7 @@
           - 'PLAT0036'
           - 'IMM0034'
           - 'PLAT0446'
+          :warning: []
           :name: Security
         :status:
           :detail:
@@ -355,11 +359,13 @@
           :warning:
           - 'IMM0012'
         :addition:
+          :critical: []
           :detail:
           - 'IMM0106'
           - 'PLAT0084'
           - 'IMM0100'
           - 'IMM0096'
+          :warning: []
 :http_proxy:
   :lenovo:
     :host:
```

**Comment by himdel** [comment]
(Thanks to @tadeboro, this will not happen again, since https://github.com/ManageIQ/manageiq-ui-classic/pull/4440, the UI can handle those arrays not existing.)

**Comment by CharlleDaniel** [comment]
@himdel good catch, thanks

**Pull request merged**
