### PR TITLE
update urijs package

### PR DESCRIPTION
**Pull request by kavyanekkalapu**
@miq-bot assign @Fryguy
@miq-bot add_reviewer @Fryguy
@miq-bot add-label security_fix

### CODE REVIEW

**Comment by Fryguy** [comment]
Does this have to go back to najdorf?

**Comment by kavyanekkalapu** [comment]
@Fryguy For now, i will add label and we can discuss in backport call.

**Comment by kavyanekkalapu** [comment]
@miq_bot add-label najdorf/yes?

**Comment by Fryguy** [comment]
Backported to `najdorf` in commit 15723a8af591c11471529b34e5dd58cf1e1cc7a3.

```text
commit 15723a8af591c11471529b34e5dd58cf1e1cc7a3
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Mar 1 11:29:42 2022 -0500

    Merge pull request #359 from kavyanekkalapu/update_urijs
    
    update urijs package
    
    (cherry picked from commit ef5058c3f239927ee51aa8e0532ec61b9684ee6e)
```

**Pull request merged**
