### PR TITLE
This cop has moved to Naming

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Comment by bdunne** [comment]
@Fryguy Please review

**Comment by bdunne** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by bdunne** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit e7211d3f17b2078da7b36d778a951f87f45e283b
Author: Rodney Brown <rodneyhbrown7@users.noreply.github.com>
Date:   Thu Jan 18 08:36:56 2018 -0500

    Merge pull request #124 from bdunne/fix_cop_namespace
    
    This cop has moved to Naming
    (cherry picked from commit 7c0e955180ed71b7d8a876c6d1026bcb6207e40c)
```

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 2c35b322c4a2c525e30332916cb02849e0380f17
Author: Rodney Brown <rodneyhbrown7@users.noreply.github.com>
Date:   Thu Jan 18 08:36:56 2018 -0500

    Merge pull request #124 from bdunne/fix_cop_namespace
    
    This cop has moved to Naming
    (cherry picked from commit 7c0e955180ed71b7d8a876c6d1026bcb6207e40c)
```

**Pull request merged**
