### PR TITLE
Parse Physical Storage

### PR DESCRIPTION
**Pull request by EsdrasVP**
This PR is able to:
- Parse Physical Storage informations and maps the relationship to Physical Racks.
- Adds storage to the /cabinet mock.

Depends on:
- [ManageIQ/manageiq-schema#196](https://github.com/ManageIQ/manageiq-schema/pull/196) [Merged]
- [ManageIQ/manageiq#17380](https://github.com/ManageIQ/manageiq/pull/17380) [Merged]

### CODE REVIEW

**Comment by skovic** [comment]
@agrare Looks like the PR that this one depends on has been merged. Have you had a chance to look at this yet? Thanks

**Comment by agrare** [comment]
@skovic this actually also depends on https://github.com/ManageIQ/manageiq/pull/17380 (which should be added to the description) and yes I'm reviewing it there

**Comment by EsdrasVP** [comment]
@skovic Sorry for that, just added the other dependency to the description

**Comment by agrare** [comment]
@EsdrasVP I'm still getting a lot of errors running the specs in this PR with https://github.com/ManageIQ/manageiq/pull/17380 applied locally.

There are basically three kinds of errors:
```
  1) ManageIQ::Providers::Lenovo::PhysicalInfraManager::RefreshParser parse config patterns will retrieve config patterns
     Failure/Error: storage = XClarityClient::Storage.new(storage_hash)
     
     ActiveModel::UnknownAttributeError:
       unknown attribute 'uuid' for Storage.
     # /home/agrare/.gem/ruby/2.4.4/gems/activemodel-5.0.7/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
     # /home/agrare/.gem/ruby/2.4.4/gems/activemodel-5.0.7/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
     # /home/agrare/.gem/ruby/2.4.4/gems/activemodel-5.0.7/lib/active_model/attribute_assignment.rb:39:in `each'
     # /home/agrare/.gem/ruby/2.4.4/gems/activemodel-5.0.7/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
     # /home/agrare/.gem/ruby/2.4.4/gems/activerecord-5.0.7/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
     # /home/agrare/.gem/ruby/2.4.4/gems/activemodel-5.0.7/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
     # /home/agrare/.gem/ruby/2.4.4/gems/activerecord-5.0.7/lib/active_record/core.rb:319:in `initialize'
     # /home/agrare/.gem/ruby/2.4.4/gems/activerecord-5.0.7/lib/active_record/inheritance.rb:65:in `new'
     # /home/agrare/.gem/ruby/2.4.4/gems/activerecord-5.0.7/lib/active_record/inheritance.rb:65:in `new'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb:13:in `parse_physical_storage'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb:45:in `parse_physical_storage'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:92:in `block (2 levels) in get_all_physical_infra'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:91:in `each'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:91:in `block in get_all_physical_infra'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:59:in `each'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:59:in `get_all_physical_infra'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:30:in `ems_inv_to_hashes'
     # ./spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb:35:in `block (2 levels) in <top (required)>'
     # ./spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb:368:in `block (3 levels) in <top (required)>'
```

This looks like a namespace issue, it is trying to reference the top-level model `Storage` instead of the `XClarityClient::Storage`

```
  2) ManageIQ::Providers::Lenovo::PhysicalInfraManager::RefreshParser parse physical storages will parse physical storage hardware data
     Failure/Error: storage = XClarityClient::Storage.new(storage_hash)
     
     NameError:
       uninitialized constant XClarityClient::Storage
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb:13:in `parse_physical_storage'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb:45:in `parse_physical_storage'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:92:in `block (2 levels) in get_all_physical_infra'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:91:in `each'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:91:in `block in get_all_physical_infra'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:59:in `each'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:59:in `get_all_physical_infra'
     # ./app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb:30:in `ems_inv_to_hashes'
     # ./spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb:35:in `block (2 levels) in <top (required)>'
     # ./spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb:94:in `block (3 levels) in <top (required)>'
```
Is there actually an `XClarityClient::Storage` class?  I tried doing
```
>> require 'xclarity_client'
=> true
>> XClarityClient
=> XClarityClient
>> XClarityClient::Storage
NameError: uninitialized constant XClarityClient::Storage
	from (irb):3
	from /home/agrare/.rubies/ruby-2.4.4/bin/irb:11:in `<main>'
>> require 'xclarity_client/storage'
LoadError: cannot load such file -- xclarity_client/storage
	from /home/agrare/.rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /home/agrare/.rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from (irb):4
	from /home/agrare/.rubies/ruby-2.4.4/bin/irb:11:in `<main>'
```

Then:
```
  41) ManageIQ::Providers::Lenovo::PhysicalInfraManager::Refresher will parse the legacy inventory
      Failure/Error: VCR.insert_cassette("#{vcr_path}/mock_aicc", options)
      
      ArgumentError:
        There is already a cassette with the same name (manageiq/providers/lenovo/physical_infra_manager/mock_aicc).  You cannot nest multiple cassettes with the same name.
      # /home/agrare/.gem/ruby/2.4.4/gems/vcr-3.0.3/lib/vcr.rb:130:in `insert_cassette'
      # ./spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb:6:in `block (2 levels) in <top (required)>'
```

**Comment by agrare** [comment]
@EsdrasVP you probably need @rodneyhbrown7 to cut a new version of the client gem

**Comment by EsdrasVP** [comment]
@agrare Yes, I can do that. I'll make the changes and amend here.

**Comment by EsdrasVP** [comment]
@agrare I implemented tests for `refresher_spec.rb`, could you check it out?

**Pull request merged**
