### PR TITLE
[WIP] Refresher modeling 

### PR DESCRIPTION
**Pull request by AndreyMenezes**
The provider code is well advanced, but can not for the workers to work.

### CODE REVIEW

**Comment by juliancheal** [comment]
Hey @AndreyMenezes are you able to rebase this PR?

**Comment by terciodemelo** [comment]
@juliancheal This branch has some problems with aren't worth the merge. We eventually chose not to continue working on it, but in another branch which we'll open another PR. You or @AndreyMenezes can close this PR without merging it.

**Comment by juliancheal** [comment]
Thanks for the update :)

**Comment by AndreyMenezes** [comment]
Julian, I really thought I'd answer you. Sorry, my bad.

2016-11-03 17:45 GMT-03:00 Julian Cheal <notifications@github.com>:

**Pull request closed without merging**
