### PR TITLE
We have this in private, it doesn't need to still be around

### PR DESCRIPTION
**Pull request by d-m-u**
The correct version of this code lives in the private folder, so this should be able to go bye bye

### CODE REVIEW

**Comment by d-m-u** [comment]
@miq-bot add_label technical_debt, cleanup

**Comment by d-m-u** [comment]
@miq-bot add-label technical debt

**Comment by d-m-u** [comment]
@agrare I'm not sure who to assign this one to

**Comment by agrare** [comment]
@d-m-u I'll take it :)

**Pull request merged**
