### PR TITLE
Pinning faker gem to 1.8.3

### PR DESCRIPTION
**Pull request by juliancheal**
faker changed dependency of i18n which conflicts with our dependency from manageiq-consumption:
stympy/faker@9128945#diff-e79a60dc6b85309ae70a6ea8261eaf95R5

### CODE REVIEW

**Comment by juliancheal** [comment]
@jrafanie This ok?

**Comment by juliancheal** [comment]
> Looks good, can you include why we're doing it?

@jrafanie Because you said to? 😂

**Comment by juliancheal** [comment]
@miq-bot assign @agrare

**Comment by agrare** [comment]
> > Looks good, can you include why we're doing it?
>
> @jrafanie Because you said to? 😂

Loool

**Comment by jrafanie** [comment]
Thanks @juliancheal

**Comment by simaishi** [comment]
Adding `gaprindashvili/yes`, as this affects gaprindashvili branch as well.

In the last build, 1.8.4 was being used. Do we not want to ping at 1.8.4?

**Comment by juliancheal** [comment]
@simaishi oh that's strange as it's always been `1.8.3` in the gemspec. @jrafanie would `1.8.4` cause you the issues you were seeing?

**Comment by simaishi** [comment]
The gemspec had `~>1.8.3`, which was resolving to `1.8.4` until `1.8.5` came out a few days ago, which caused the problem.

`1.8.4` requires `i18n ~> 0.5`

**Comment by jrafanie** [comment]
1.8.5 is the problem version so 1.8.4 should be fine to use @juliancheal

**Comment by juliancheal** [comment]
@jrafanie @simaishi cool beans. Ok `1.8.4` it is. Thanks @simaishi :)

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 108d4801ef8edd0760f33b01951f17a67a05d7a0
Author: Adam Grare <agrare@redhat.com>
Date:   Thu Dec 7 10:59:55 2017 -0500

    Merge pull request #118 from juliancheal/pin_faker_gem
    
    Pinning faker gem to 1.8.3
    (cherry picked from commit 7d0ed913905806800584dc6d3a8526310eea597d)
```

**Comment by chargio** [comment]
We can update the dependency on manageiq-consumption, if it is better.

**Comment by jrafanie** [comment]
@chargio It's not mutually exclusive.  This change requires no other changes.  We can now upgrade manageiq-consumption at our convenience and then decide if we want to loosen the dependency requirement here.

**Pull request merged**
