### PR TITLE
[WIP] Split network ports parser (#9)

### PR DESCRIPTION
**Pull request by caiocmpaes**
**What this PR does:**
- Splits the `PhysicalNetworkPortsParser` into two classes `PhysicalNetworkPortsParser` & `PhysicalSwitchPortsParser`, because this parser had two different entry points and no reuse.

**Reason:**
- The PhysicalNetworkPortsParser had two public methods. One for parsing switches ports and other for parsing server network ports. There was no reuse or cause for them to be together in a single class.

**Depends on:**
- #184

### CODE REVIEW

**Comment by caiocmpaes** [comment]
@miq-bot add_label refactoring

**Comment by caiocmpaes** [comment]
@miq-bot remove_label unmergeable

**Comment by caiocmpaes** [comment]
@miq-bot remove_label unmergeable

**Comment by douglasgabriel** [comment]
Since there are some common routines on switches and servers ports parsers, like bind_network_ports!, for example, me and @felipedf agree that split these parsers this way is not the better approach. So I'm closing this PR for now until we figure out a better way to improve the network ports parser.

**Pull request closed without merging**
