### PR TITLE
Removing out of date code

### PR DESCRIPTION
**Pull request by douglasgabriel**
**This PR removes:**
* Out of date code added in this PR: https://github.com/ManageIQ/manageiq-providers-lenovo/pull/93

This code was moved to [parse.rb](https://github.com/ManageIQ/manageiq-providers-lenovo/blob/master/app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb) in this PR: https://github.com/ManageIQ/manageiq-providers-lenovo/pull/98

### CODE REVIEW

**Comment by douglasgabriel** [comment]
Hey @agrare, could you take a look on this?

**Comment by douglasgabriel** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by agrare** [comment]
@douglasgabriel does this need to be in gaprindashvili ?  Is it causing an error in refresh?

**Comment by douglasgabriel** [comment]
Not really @agrare. It just clean this amount of duplicated code

**Comment by agrare** [comment]
👍 thanks were only taking blockers only for the first g release so this will get picked up in g-2

**Comment by simaishi** [comment]
@douglasgabriel  @agrare https://github.com/ManageIQ/manageiq-providers-lenovo/pull/98 isn't marked as `gaprindasvhili/yes`, so I assume we don't need this PR?

**Comment by agrare** [comment]
@simaishi I don't think we need this or https://github.com/ManageIQ/manageiq-providers-lenovo/pull/98 in gaprindashvili since that was refactoring

**Comment by simaishi** [comment]
Thanks Adam, removing the label.

**Pull request merged**
