### PR TITLE
refactoring of refresh

### PR DESCRIPTION
**Pull request by juliancheal**
Added Firmware model

Started to extract attributes to add to other tables such as:
hardwares, networks, etc.

### CODE REVIEW

**Comment by rodneyhbrown7** [comment]
For the Lenovo team, this preps our refresher for broader support of the hardware model.  I don't think this significantly changes how we populate the attributes of the physical_server.

**Comment by juliancheal** [comment]
> For the Lenovo team, this preps our refresher for broader support of the hardware model. I don't think this significantly changes how we populate the attributes of the physical_server.

Think I get what you're saying. It's mainly the `mac address` & `ip addresses` that I'm extracting out to store in `Networks` via `Hardwares`.

**Comment by juliancheal** [comment]
@miq-bot remove_label wip

**Comment by juliancheal** [comment]
@blomquisg this is ready to merge (nb. lack of tests that will come in a follow up PR).

**Comment by juliancheal** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 08331b54b5fa81f2d0f77704986c06cc5c6a2517
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Tue Apr 4 12:58:07 2017 -0400

    Merge pull request #34 from juliancheal/refactor_refresh
    
    refactoring of refresh
    (cherry picked from commit e92dc1f7e335cca6fd8968aa2f9bcca2c5f0017d)
```

**Pull request merged**
