### PR TITLE
Change device_type from 'ethernet port' to 'physical_port'

### PR DESCRIPTION
**Pull request by skovic**
Updated the device_type for ethernet ports to be 'physical_port' instead of 'ethernet port' due to pending changes in the model.

### CODE REVIEW

**Comment by juliancheal** [comment]
@skovic do you want to wait for the model to be changed first before we merge this?

**Comment by skovic** [comment]
@juliancheal Yes, we would like for the model changes to go in first. Thanks

**Comment by blomquisg** [comment]
https://github.com/ManageIQ/manageiq/pull/15371 is merged ... Merging this to adjust the refresher so it sets the correct device type.

**Comment by juliancheal** [comment]
Thanks @blomquisg!

**Pull request merged**
