### PR TITLE
Update provider to support network adapters

### PR DESCRIPTION
**Pull request by skovic**
Made changes to the refresh_parser to support the parsing of network adapter details.

### CODE REVIEW

**Comment by skovic** [comment]
@miq-bot add_label wip

**Comment by skovic** [comment]
@miq-bot remove_label wip

**Comment by skovic** [comment]
@juliancheal When you get a chance, could you take a look at this? Thanks

**Comment by juliancheal** [comment]
LGTM 👍 want me to merge it @skovic?

**Comment by skovic** [comment]
@juliancheal Yes, that would be great. Thanks

**Pull request merged**
