### PR TITLE
Parse provider and save(MIQ) Processor and memory infomation

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This PR is able to:
- Save total memories
- Save total cores

### CODE REVIEW

**Comment by rodneyhbrown7** [comment]
Maysa, how does this PR differ from   https://github.com/ManageIQ/manageiq-providers-lenovo/pull/35 ? Have you seen that PR?

**Comment by walteraa** [comment]
@rodneyhbrown7 the PR #35 is unmergeble because don't use the new structure proposed by @juliancheal, which the hardware relationship is accessed and saved  through Compute System. The #35 should be closed.

**Comment by rodneyhbrown7** [comment]
If you look at 35 it also sets the power_state, health_state and the vendor.    The power_state and vendor fields need to be merged to support https://github.com/ManageIQ/manageiq-ui-classic/pull/755.  Will those be added to this PR?

**Comment by walteraa** [comment]
No, `power_state` and `health_state` should be defined in other PR. Maybe we can change the #35 in a PR to set this properties. What do you think @odravison?

**Comment by juliancheal** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
@MaysaMacedo @juliancheal It looks like this PR depends on https://github.com/ManageIQ/manageiq-providers-lenovo/pull/34, which isn't marked as `fine/yes`. Should I backport https://github.com/ManageIQ/manageiq-providers-lenovo/pull/34 as well?

**Comment by juliancheal** [comment]
@simaishi Yes, sorry was just going through making sure all our PRs are marked with `fine/yes` that should be.

**Comment by simaishi** [comment]
Fine backport details:

```
 $ git log -1
commit 60c869c022c1993ae6b1fdc2b27be9c6de252e20
Author: Julian Cheal <julian.cheal@gmail.com>
Date:   Tue Apr 11 12:42:27 2017 +0100

    Merge pull request #39 from MaysaMacedo/XCS-166
    
    Parse provider and save(MIQ) Processor and memory infomation
    (cherry picked from commit 7668a5f296006c47140278b4a5afcebd91c315db)
```

**Pull request merged**
